# Generated by Django 4.2 on 2023-04-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Fecha_Finalizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Fecha_Inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
