# Generated by Django 4.2 on 2023-05-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Fecha_Inicio',
        ),
    ]
